import {createRequire} from 'node:module';
import fs from 'node:fs/promises';
const require=createRequire(process.env.D01_WEB_PACKAGE||'C:/Users/yxy/Desktop/work/AI_FOR_VECTOR/web/package.json');const {chromium}=require('playwright');
const browser=await chromium.launch({headless:true,channel:'chrome'});
const base='http://127.0.0.1:18404/prototype.html',p='18cb3488-119b-4d8d-958f-e20a0a70d0ae',l='76375d7a-74cf-4c2b-b0e0-d724afaec1d9',ctx=`?projectId=${p}&layerId=${l}`;
const results=[],network=[],errors=[],performanceRecords=[];
async function check(name,fn){try{const detail=await fn();results.push({name,pass:true,detail});console.log('PASS '+name);}catch(e){results.push({name,pass:false,error:e.message});console.log('FAIL '+name+' '+e.message);}}
function assert(value,msg){if(!value)throw Error(msg);}
const page=await browser.newPage({viewport:{width:1440,height:900},deviceScaleFactor:1});page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>network.push({method:r.method(),url:r.url()}));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
async function go(route,query=ctx){await page.goto(base+'#/'+route+query);await page.waitForFunction(()=>window.D01?.ready);await page.waitForTimeout(220);}
async function nav(id){await page.locator(`[data-feature="${id}"]`).click();}
await check('actual models load / one canvas',async()=>{await go('home');const m=await page.evaluate(()=>D01.metrics());assert(m.ready&&m.canvasCount===1,'GLB or single canvas failed');return m;});
await check('idle moves cube with independent root / reduced angular speed envelope',async()=>{const samples=[];for(let i=0;i<5;i++){samples.push(await page.evaluate(()=>D01.metrics().cubeQuaternion));await page.waitForTimeout(220);}assert(JSON.stringify(samples[0])!==JSON.stringify(samples[4]),'cube stationary');const independence=await page.evaluate(()=>{const s=D01.getScene();return {parent:s.cube.parent.type,robotParent:s.robot.parent.type,handBinding:s.cube.parent!==s.robot};});assert(independence.handBinding,'cube attached to robot');return {samples,independence};});
await check('six face normals align with camera',async()=>{const values=[];for(const id of ['projects','data','analysis','tasks','exports','overview']){await nav(id);await page.waitForTimeout(950);const m=await page.evaluate(()=>D01.metrics());assert(m.feature===id&&m.faceDotView>.999,'misaligned '+id);assert(await page.locator('#preview-title').innerText(), 'missing title');values.push({id,dot:m.faceDotView,source:m.faceSourceScreen,quad:m.projectionQuad});}return values;});
await check('preview holds at 1.5 and 3 seconds / no auto expansion',async()=>{await nav('analysis');await page.waitForTimeout(1500);const first=await page.evaluate(()=>({m:D01.metrics(),s:D01.state.mode}));await page.waitForTimeout(1650);const last=await page.evaluate(()=>({m:D01.metrics(),s:D01.state.mode}));assert(first.s==='preview'&&last.s==='preview','auto-expanded');assert(JSON.stringify(first.m.cubeQuaternion)===JSON.stringify(last.m.cubeQuaternion),'cube moved while reading');return {first:first.m,last:last.m};});
await check('explicit expand / heading focus / project and layer continuity',async()=>{await page.locator('#expand').click();await page.waitForTimeout(650);const info=await page.evaluate(()=>({mode:D01.state.mode,project:D01.state.projectId,layer:D01.state.layerId,focus:document.activeElement.id,canvas:document.querySelectorAll('canvas').length}));assert(info.mode==='work'&&info.project===p&&info.layer===l&&info.focus==='workspace-title'&&info.canvas===1,'context/focus changed');return info;});
await check('seven tool forms / invalid and valid checks / no fabricated result',async()=>{const toolIds=['buffer','clip','intersection','dissolve','spatial-join','validate-repair','point-in-polygon'];for(const id of toolIds){await page.locator(`[data-tool="${id}"]`).click();assert(await page.locator('#analysis-layer').count()===1,'missing layer '+id);}await page.locator('[data-tool="buffer"]').click();await page.locator('#distance').fill('-10');await page.locator('#output-name').fill('城市_500米');await page.locator('#analysis-form button[type=submit]').click();assert((await page.locator('#analysis-feedback').innerText()).includes('大于 0'),'invalid distance passed');await page.locator('#distance').fill('500');await page.locator('#analysis-form button[type=submit]').click();const text=await page.locator('#analysis-feedback').innerText();assert(text.includes('尚未提交'),'missing honest feedback');return {tools:toolIds,feedback:text};});
await check('work-to-work navigation is immediate and keeps canvas',async()=>{const before=await page.evaluate(()=>D01.metrics().rendered);await nav('exports');const s=await page.evaluate(()=>({mode:D01.state.mode,id:D01.state.feature,canvas:document.querySelectorAll('canvas').length,rendered:D01.metrics().rendered}));assert(s.mode==='work'&&s.id==='exports'&&s.canvas===1,'replayed hero');return {before,...s};});
await check('export CRS / all-excluded fields / local feedback',async()=>{await page.locator('#crs').fill('0');await page.locator('#export-form button[type=submit]').click();assert((await page.locator('#export-feedback').innerText()).includes('正整数'),'invalid EPSG passed');await page.locator('#crs').fill('4326');for(const field of await page.locator('[data-field]').all())await field.uncheck();await page.locator('#export-form button[type=submit]').click();assert((await page.locator('#export-feedback').innerText()).includes('至少保留'),'empty fields passed');await page.locator('[data-field]').first().check();await page.locator('#export-form button[type=submit]').click();return await page.locator('#export-feedback').innerText();});
await check('data filter / unbound table identity / no invented extent',async()=>{await nav('data');await page.locator('#data-kind').selectOption('table');await page.locator('[data-data]').first().click();const text=await page.locator('#workspace-body').innerText();assert(text.includes('未绑定项目')&&text.includes('没有图层 ID 与空间范围'),'unbound table attached');await page.locator('#data-search').fill('missing-does-not-exist');assert((await page.locator('#workspace-body').innerText()).includes('没有匹配的数据'),'missing empty state');return 'unbound table and empty search visible';});
await check('task state filter / logs and historical error',async()=>{await nav('tasks');await page.locator('#task-state').selectOption('failed');await page.locator('[data-task]').first().click();const txt=await page.locator('.log-panel').innerText();assert(txt.includes('upstream_data_error'),'missing actual error');await page.locator('#task-state').selectOption('running');assert((await page.locator('#workspace-body').innerText()).includes('没有任务记录'),'invented live tasks');return txt;});
await check('overview retains global totals under project selector',async()=>{await nav('overview');const text=await page.locator('.stat-line').innerText();assert(text.includes('2')&&text.includes('4'),'global counts missing');return text;});
await check('Escape / focus returns to invoking navigation',async()=>{await page.keyboard.press('Escape');const info=await page.evaluate(()=>({mode:D01.state.mode,focus:document.activeElement.dataset.feature}));assert(info.mode==='home'&&info.focus==='overview','bad focus return');return info;});
await check('rapid selection and expansion interruption',async()=>{await nav('analysis');await page.waitForTimeout(70);await nav('tasks');await page.waitForTimeout(70);await nav('exports');await page.waitForTimeout(900);assert(await page.evaluate(()=>D01.state.feature==='exports'),'stale transition won');await page.locator('#expand').click();await page.waitForTimeout(100);await page.keyboard.press('Escape');await page.waitForTimeout(650);assert(await page.evaluate(()=>D01.state.mode==='home'),'stale expand callback');return 'latest choice wins; Escape cancels pending expansion';});
await check('browser back restores preview / deep link enters page',async()=>{await go('home');await nav('analysis');await page.waitForTimeout(950);await page.locator('#expand').click();await page.waitForTimeout(650);await nav('exports');await page.goBack();assert(await page.evaluate(()=>D01.state.feature==='analysis'&&D01.state.mode==='work'),'back did not restore work');await page.goBack();assert(await page.evaluate(()=>D01.state.mode==='preview'),'back did not restore preview');await go('analysis','');assert(await page.evaluate(()=>D01.state.projectId===''&&D01.state.layerId===''&&D01.state.mode==='work'),'deep link defaulted project');return 'direct entry and both history steps verified';});
await check('invalid / cross-project context clears rather than reassigns',async()=>{await go('analysis','?projectId=fbfb2263-187a-4e57-b34f-385557cf04a0&layerId='+l);assert(await page.evaluate(()=>D01.state.layerId===''),'cross project layer not cleared');await go('analysis','?projectId=missing&layerId=missing');assert(await page.evaluate(()=>D01.state.projectId===''&&D01.state.layerId===''),'invalid context retained');return 'project/layer invalidation shown';});
await check('explicit home layer selection creates meaningful spatial foreground',async()=>{await go('home','');await page.locator('#home-project').selectOption(p);assert(await page.evaluate(()=>D01.state.layerId===''),'first layer silently selected');await page.locator('#home-layer').selectOption(l);await page.waitForTimeout(200);assert(await page.evaluate(()=>D01.getScene().mapRoot.visible),'map absent');await nav('analysis');await page.waitForTimeout(900);assert(await page.locator('#preview-map svg').count()===1,'preview lacks real map');return 'project selection is separate from explicit observation layer';});
await check('reduced motion reaches usable final preview; no frame loop',async()=>{await page.emulateMedia({reducedMotion:'reduce'});await nav('data');await page.waitForTimeout(80);const a=await page.evaluate(()=>D01.metrics());await page.waitForTimeout(500);const b=await page.evaluate(()=>D01.metrics());assert(b.reduced&&b.faceDotView>.999,'reduced transition failed');assert(a.rendered===b.rendered,'reduced rendering continues');await page.locator('#expand').click();await page.waitForTimeout(50);assert(await page.evaluate(()=>D01.state.mode==='work'),'reduced expand stuck');await page.emulateMedia({reducedMotion:'no-preference'});return {frames:[a.rendered,b.rendered]};});
await check('1280×720 safe areas / 390 and 844×390 no horizontal overflow',async()=>{const sizes=[];for(const size of [{width:1280,height:720},{width:390,height:844},{width:844,height:390}]){await page.setViewportSize(size);await go('home');if(size.width===1280){const overlap=await page.evaluate(()=>{const a=document.querySelector('.home-intro').getBoundingClientRect(),b=document.querySelector('#navigation').getBoundingClientRect();return a.bottom>b.top&&a.left<b.right;});assert(!overlap,'intro overlaps navigation');}for(const route of ['home','preview/analysis','analysis','projects','data','tasks','exports','overview']){await go(route);const dims=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,body:document.body.scrollWidth}));assert(dims.scroll<=size.width+1&&dims.body<=size.width+1,`${route} overflow ${JSON.stringify(dims)}`);sizes.push({size,route,...dims});}}return sizes;});
await check('mobile navigation touch targets and selected close button >=44',async()=>{await page.setViewportSize({width:390,height:844});await go('home');await page.locator('#menu-toggle').click();const boxes=await page.locator('#navigation a').evaluateAll(nodes=>nodes.map(n=>{const r=n.getBoundingClientRect();return {text:n.textContent.trim(),w:r.width,h:r.height};}));assert(boxes.every(x=>x.h>=44&&x.w>=44),'small touch navigation');await nav('analysis');const cancel=await page.locator('#cancel-preview').boundingBox();assert(cancel.height>=44&&cancel.width>=44,'small cancel control');return {boxes,cancel};});
await check('model failure retains usable navigation and forms',async()=>{const fallback=await browser.newPage({viewport:{width:1280,height:720}});await fallback.route('**/assets/*.glb',r=>r.abort());await fallback.goto(base+'#/analysis'+ctx);await fallback.waitForFunction(()=>window.D01?.ready);assert(await fallback.locator('body.static-scene').count()===1,'no static fallback');await fallback.locator('#output-name').fill('失败降级验证');await fallback.locator('#analysis-form button[type=submit]').click();assert((await fallback.locator('#analysis-feedback').innerText()).includes('尚未提交'),'forms lost in fallback');await fallback.screenshot({path:'evidence/model-fallback.png'});await fallback.close();return 'blocked GLBs; same-asset fallback with interactive form';});
await check('data failure and empty snapshot states remain usable',async()=>{const failed=await browser.newPage();await failed.route('**/data/snapshot.json',r=>r.fulfill({status:503,body:'unavailable'}));await failed.goto(base+'#/projects');await failed.waitForFunction(()=>window.D01?.ready);assert((await failed.locator('#workspace-body').innerText()).includes('没有匹配'),'no data-error empty state');await failed.close();return 'snapshot failure does not lock navigation';});
await check('offline-resource package / no network APIs or write methods',async()=>{const external=network.filter(r=>!r.url.startsWith('http://127.0.0.1:18404/')&&!r.url.startsWith('blob:')&&!r.url.startsWith('data:'));assert(external.length===0,'external requests');assert(network.every(r=>r.method==='GET'),'write request');const isolated=await browser.newPage();await isolated.route('**/*',route=>route.request().url().startsWith('http://127.0.0.1:18404/')?route.continue():route.abort());await isolated.goto(base+'#/home'+ctx);await isolated.waitForFunction(()=>window.D01?.ready);assert((await isolated.evaluate(()=>D01.metrics())).ready,'offline-resource model failure');await isolated.close();return {external,requests:network.length,methods:[...new Set(network.map(r=>r.method))]};});
await check('measured performance / actual viewports and DPR',async()=>{for(const [size,dpr]of [[{width:1440,height:900},1.5],[{width:1920,height:1080},1.5],[{width:390,height:844},2]]){const performancePage=await browser.newPage({viewport:size,deviceScaleFactor:dpr});await performancePage.goto(base+'#/home'+ctx);await performancePage.waitForFunction(()=>window.D01?.ready);await performancePage.waitForTimeout(4100);const metrics=await performancePage.evaluate(()=>D01.metrics());assert(metrics.frameSamples>100,'insufficient samples');performanceRecords.push(metrics);await performancePage.close();}return performanceRecords;});
await check('URL restoration refreshes the actual scene layer after global scope',async()=>{await page.setViewportSize({width:1920,height:1080});await go('overview');await page.locator('#work-project').selectOption('');await go('home');const x=await page.evaluate(()=>({sceneLayer:D01.getScene().layer?.id,routeLayer:D01.state.layerId,mapVisible:D01.getScene().mapRoot.visible}));assert(x.sceneLayer===l&&x.routeLayer===l&&x.mapVisible,'URL and scene layer diverged');return x;});
await check('no unexpected console or page errors',async()=>{assert(errors.length===0,errors.join('\n'));return errors;});
const report={version:'D01-R1',createdAt:new Date().toISOString(),browser:await browser.version(),platform:process.platform,node:process.version,passed:results.filter(r=>r.pass).length,failed:results.filter(r=>!r.pass).length,results,performance:performanceRecords,errors,networkSummary:{requests:network.length,external:network.filter(r=>!r.url.startsWith('http://127.0.0.1:18404/')&&!r.url.startsWith('blob:')),methods:[...new Set(network.map(r=>r.method))]},scope:'Design prototype only. Read-only snapshot; no production GIS/OL performance claim.'};
await fs.writeFile('evidence/qa-report.json',JSON.stringify(report,null,2));await browser.close();console.log(JSON.stringify({passed:report.passed,failed:report.failed}));if(report.failed)process.exitCode=1;
